/********************************************************************************
** Form generated from reading UI file 'imgtoolgui.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_IMGTOOLGUI_H
#define UI_IMGTOOLGUI_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QTabWidget>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ImgToolGUIClass
{
public:
    QAction *btnMenuOpenFile;
    QAction *btnMenuExit;
    QWidget *centralwidget;
    QLabel *lblMainTitle;
    QLineEdit *txtFilePath;
    QLabel *lblFilePath;
    QTabWidget *tabImg3;
    QWidget *tab;
    QLabel *lblImgFullSize;
    QLineEdit *txtImg3FullSize;
    QLabel *lblImgVersionTab;
    QLineEdit *txtImg3Version;
    QLabel *lblImgFullSizeNoHeader;
    QLineEdit *txtImg3FullSizeNoHeader;
    QLabel *lblImg3SignatureCheckArea;
    QLineEdit *txtImg3SignatureCheckArea;
    QLabel *lblImg3ID;
    QLineEdit *txtImg3ID;
    QWidget *tab_10;
    QLabel *lblImg3TagTYPE;
    QLineEdit *txtImg3TagTYPE;
    QLabel *lblImg3TotalLengthTYPE;
    QLineEdit *txtImg3TotalLengthTYPE;
    QLabel *lblImg3LengthTagTYPE;
    QLineEdit *txtImg3DataLengthTYPE;
    QWidget *tab_11;
    QLabel *lblImg3TagDATA;
    QLineEdit *txtImg3TagDATA;
    QLabel *lblImg3TotalLengthDATA;
    QLineEdit *txtImg3TotalLengthDATA;
    QLabel *lblImg3DataLengthDATA;
    QLineEdit *txtImg3DataLengthDATA;
    QTabWidget *tabCode;
    QWidget *tab_8;
    QLabel *lblImageInfo;
    QLineEdit *txtImageInfo;
    QLabel *lblImageSecurityFusing;
    QLineEdit *txtImageSecurityFusing;
    QLabel *lblImageVersion;
    QLineEdit *txtImageVersion;
    QPushButton *btnExportImage;
    QWidget *tab_2;
    QLineEdit *txtImg3TagVERS;
    QLabel *lblImg3TagVERS;
    QLabel *lblImg3TotalLengthVERS;
    QLabel *lblImg3DataLengthVERS;
    QLineEdit *txtImg3TotalLengthVERS;
    QLineEdit *txtImg3DataLengthVERS;
    QLabel *lblImg3DataVERS;
    QLineEdit *txtImg3DataVERS;
    QWidget *tab_3;
    QLineEdit *txtImg3TotalLengthSEPO;
    QLineEdit *txtImg3DataLengthSEPO;
    QLineEdit *txtImg3TagSEPO;
    QLabel *lblImg3DataLengthSEPO;
    QLabel *lblImg3TagSEPO;
    QLabel *lblImg3TotalLengthSEPO;
    QLabel *lblImg3DataSEPO;
    QLineEdit *txtImg3DataSEPO;
    QWidget *tab_4;
    QLabel *lblImg3DataCHIP;
    QLabel *lblImg3TotalLengthCHIP;
    QLineEdit *txtImg3TotalLengthCHIP;
    QLineEdit *txtImg3TagCHIP;
    QLineEdit *txtImg3DataCHIP;
    QLabel *lblImg3TagCHIP;
    QLineEdit *txtImg3DataLengthCHIP;
    QLabel *lblImg3DataLengthCHIP;
    QWidget *tab_5;
    QLabel *lblImg3DataLengthBORD;
    QLineEdit *txtImg3TagBORD;
    QLineEdit *txtImg3TotalLengthBORD;
    QLineEdit *txtImg3DataBORD;
    QLabel *lblImg3TagBORD;
    QLabel *lblImg3TotalLengthBORD;
    QLineEdit *txtImg3DataLengthBORD;
    QLabel *lblImg3DataBORD;
    QWidget *tab_6;
    QLabel *lblImg3TotalLengthSHSH;
    QLineEdit *txtImg3DataLengthSHSH;
    QLineEdit *txtImg3TagSHSH;
    QLabel *lblImg3DataLengthSHSH;
    QLineEdit *txtImg3DataSHSH;
    QLabel *lblImg3TagSHSH;
    QLabel *lblImg3DataSHSH;
    QLineEdit *txtImg3TotalLengthSHSH;
    QWidget *tab_7;
    QLineEdit *txtImg3TagCERT;
    QLineEdit *txtImg3TotalLengthCERT;
    QLineEdit *txtImg3DataLengthCERT;
    QLabel *lblImg3DataLengthCERT;
    QLabel *lblImg3TotalLengthCERT;
    QLabel *lblImg3TagCERT;
    QPushButton *btnExportCert;
    QTabWidget *tabCERT;
    QWidget *tab_13;
    QLineEdit *txtImg3TagSDOM;
    QLabel *lblImg3TagSDOM;
    QLabel *lblImg3DataLengthSDOM;
    QLineEdit *txtImg3DataLengthSDOM;
    QLineEdit *txtImg3TotalLengthSDOM;
    QLabel *lblImg3TotalLengthSDOM;
    QLabel *lblImg3DataSDOM;
    QLineEdit *txtImg3DataSDOM;
    QWidget *tab_14;
    QLineEdit *txtImg3TagPROD;
    QLabel *lblImg3TagPROD;
    QLabel *lblImg3DataLengthPROD;
    QLineEdit *txtImg3DataLengthPROD;
    QLabel *lblImg3TotalLengthPROD;
    QLineEdit *txtImg3TotalLengthPROD;
    QLineEdit *txtImg3DataPROD;
    QLabel *lblImg3DataPROD;
    QWidget *tab_15;
    QLabel *lblImg3DataCHIPcert;
    QLabel *lblImg3TagCHIPcert;
    QLineEdit *txtImg3TotalLengthCHIPcert;
    QLineEdit *txtImg3TagCHIPcert;
    QLineEdit *txtImg3DataCHIPcert;
    QLabel *lblImg3TotalLengthCHIPcert;
    QLineEdit *txtImg3DataLengthCHIPcert;
    QLabel *lblImg3DataLengthCHIPcert;
    QLabel *lblImgVersion;
    QLineEdit *txtImgVersion;
    QLabel *lblSoftwareVersion;
    QLabel *lblCopyrights;
    QMenuBar *menubar;
    QMenu *menuFile;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *ImgToolGUIClass)
    {
        if (ImgToolGUIClass->objectName().isEmpty())
            ImgToolGUIClass->setObjectName(QString::fromUtf8("ImgToolGUIClass"));
        ImgToolGUIClass->resize(544, 582);
        btnMenuOpenFile = new QAction(ImgToolGUIClass);
        btnMenuOpenFile->setObjectName(QString::fromUtf8("btnMenuOpenFile"));
        btnMenuExit = new QAction(ImgToolGUIClass);
        btnMenuExit->setObjectName(QString::fromUtf8("btnMenuExit"));
        centralwidget = new QWidget(ImgToolGUIClass);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        lblMainTitle = new QLabel(centralwidget);
        lblMainTitle->setObjectName(QString::fromUtf8("lblMainTitle"));
        lblMainTitle->setGeometry(QRect(90, 0, 140, 45));
        QFont font;
        font.setFamily(QString::fromUtf8("Ubuntu"));
        font.setPointSize(24);
        lblMainTitle->setFont(font);
        txtFilePath = new QLineEdit(centralwidget);
        txtFilePath->setObjectName(QString::fromUtf8("txtFilePath"));
        txtFilePath->setGeometry(QRect(140, 60, 381, 31));
        txtFilePath->setReadOnly(true);
        lblFilePath = new QLabel(centralwidget);
        lblFilePath->setObjectName(QString::fromUtf8("lblFilePath"));
        lblFilePath->setGeometry(QRect(20, 70, 121, 17));
        tabImg3 = new QTabWidget(centralwidget);
        tabImg3->setObjectName(QString::fromUtf8("tabImg3"));
        tabImg3->setGeometry(QRect(20, 140, 504, 364));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        lblImgFullSize = new QLabel(tab);
        lblImgFullSize->setObjectName(QString::fromUtf8("lblImgFullSize"));
        lblImgFullSize->setGeometry(QRect(20, 70, 91, 17));
        txtImg3FullSize = new QLineEdit(tab);
        txtImg3FullSize->setObjectName(QString::fromUtf8("txtImg3FullSize"));
        txtImg3FullSize->setEnabled(true);
        txtImg3FullSize->setGeometry(QRect(80, 60, 81, 31));
        txtImg3FullSize->setReadOnly(true);
        lblImgVersionTab = new QLabel(tab);
        lblImgVersionTab->setObjectName(QString::fromUtf8("lblImgVersionTab"));
        lblImgVersionTab->setGeometry(QRect(20, 30, 91, 17));
        txtImg3Version = new QLineEdit(tab);
        txtImg3Version->setObjectName(QString::fromUtf8("txtImg3Version"));
        txtImg3Version->setGeometry(QRect(80, 20, 51, 31));
        txtImg3Version->setReadOnly(true);
        lblImgFullSizeNoHeader = new QLabel(tab);
        lblImgFullSizeNoHeader->setObjectName(QString::fromUtf8("lblImgFullSizeNoHeader"));
        lblImgFullSizeNoHeader->setGeometry(QRect(20, 110, 181, 17));
        txtImg3FullSizeNoHeader = new QLineEdit(tab);
        txtImg3FullSizeNoHeader->setObjectName(QString::fromUtf8("txtImg3FullSizeNoHeader"));
        txtImg3FullSizeNoHeader->setGeometry(QRect(180, 100, 81, 31));
        txtImg3FullSizeNoHeader->setReadOnly(true);
        lblImg3SignatureCheckArea = new QLabel(tab);
        lblImg3SignatureCheckArea->setObjectName(QString::fromUtf8("lblImg3SignatureCheckArea"));
        lblImg3SignatureCheckArea->setGeometry(QRect(20, 150, 141, 17));
        txtImg3SignatureCheckArea = new QLineEdit(tab);
        txtImg3SignatureCheckArea->setObjectName(QString::fromUtf8("txtImg3SignatureCheckArea"));
        txtImg3SignatureCheckArea->setGeometry(QRect(180, 140, 81, 31));
        txtImg3SignatureCheckArea->setReadOnly(true);
        lblImg3ID = new QLabel(tab);
        lblImg3ID->setObjectName(QString::fromUtf8("lblImg3ID"));
        lblImg3ID->setGeometry(QRect(20, 190, 81, 17));
        txtImg3ID = new QLineEdit(tab);
        txtImg3ID->setObjectName(QString::fromUtf8("txtImg3ID"));
        txtImg3ID->setGeometry(QRect(90, 180, 81, 31));
        txtImg3ID->setReadOnly(true);
        tabImg3->addTab(tab, QString());
        tab_10 = new QWidget();
        tab_10->setObjectName(QString::fromUtf8("tab_10"));
        lblImg3TagTYPE = new QLabel(tab_10);
        lblImg3TagTYPE->setObjectName(QString::fromUtf8("lblImg3TagTYPE"));
        lblImg3TagTYPE->setGeometry(QRect(20, 30, 91, 17));
        txtImg3TagTYPE = new QLineEdit(tab_10);
        txtImg3TagTYPE->setObjectName(QString::fromUtf8("txtImg3TagTYPE"));
        txtImg3TagTYPE->setGeometry(QRect(130, 20, 81, 31));
        txtImg3TagTYPE->setReadOnly(true);
        lblImg3TotalLengthTYPE = new QLabel(tab_10);
        lblImg3TotalLengthTYPE->setObjectName(QString::fromUtf8("lblImg3TotalLengthTYPE"));
        lblImg3TotalLengthTYPE->setGeometry(QRect(20, 110, 111, 17));
        txtImg3TotalLengthTYPE = new QLineEdit(tab_10);
        txtImg3TotalLengthTYPE->setObjectName(QString::fromUtf8("txtImg3TotalLengthTYPE"));
        txtImg3TotalLengthTYPE->setGeometry(QRect(130, 100, 81, 31));
        txtImg3TotalLengthTYPE->setReadOnly(true);
        lblImg3LengthTagTYPE = new QLabel(tab_10);
        lblImg3LengthTagTYPE->setObjectName(QString::fromUtf8("lblImg3LengthTagTYPE"));
        lblImg3LengthTagTYPE->setGeometry(QRect(20, 70, 91, 17));
        txtImg3DataLengthTYPE = new QLineEdit(tab_10);
        txtImg3DataLengthTYPE->setObjectName(QString::fromUtf8("txtImg3DataLengthTYPE"));
        txtImg3DataLengthTYPE->setGeometry(QRect(130, 60, 81, 31));
        txtImg3DataLengthTYPE->setReadOnly(true);
        tabImg3->addTab(tab_10, QString());
        tab_11 = new QWidget();
        tab_11->setObjectName(QString::fromUtf8("tab_11"));
        lblImg3TagDATA = new QLabel(tab_11);
        lblImg3TagDATA->setObjectName(QString::fromUtf8("lblImg3TagDATA"));
        lblImg3TagDATA->setGeometry(QRect(20, 30, 91, 17));
        txtImg3TagDATA = new QLineEdit(tab_11);
        txtImg3TagDATA->setObjectName(QString::fromUtf8("txtImg3TagDATA"));
        txtImg3TagDATA->setGeometry(QRect(130, 20, 81, 31));
        txtImg3TagDATA->setReadOnly(true);
        lblImg3TotalLengthDATA = new QLabel(tab_11);
        lblImg3TotalLengthDATA->setObjectName(QString::fromUtf8("lblImg3TotalLengthDATA"));
        lblImg3TotalLengthDATA->setGeometry(QRect(20, 110, 111, 17));
        txtImg3TotalLengthDATA = new QLineEdit(tab_11);
        txtImg3TotalLengthDATA->setObjectName(QString::fromUtf8("txtImg3TotalLengthDATA"));
        txtImg3TotalLengthDATA->setGeometry(QRect(130, 100, 81, 31));
        txtImg3TotalLengthDATA->setReadOnly(true);
        lblImg3DataLengthDATA = new QLabel(tab_11);
        lblImg3DataLengthDATA->setObjectName(QString::fromUtf8("lblImg3DataLengthDATA"));
        lblImg3DataLengthDATA->setGeometry(QRect(20, 70, 91, 17));
        txtImg3DataLengthDATA = new QLineEdit(tab_11);
        txtImg3DataLengthDATA->setObjectName(QString::fromUtf8("txtImg3DataLengthDATA"));
        txtImg3DataLengthDATA->setGeometry(QRect(130, 60, 81, 31));
        txtImg3DataLengthDATA->setReadOnly(true);
        tabCode = new QTabWidget(tab_11);
        tabCode->setObjectName(QString::fromUtf8("tabCode"));
        tabCode->setGeometry(QRect(20, 150, 461, 164));
        tab_8 = new QWidget();
        tab_8->setObjectName(QString::fromUtf8("tab_8"));
        lblImageInfo = new QLabel(tab_8);
        lblImageInfo->setObjectName(QString::fromUtf8("lblImageInfo"));
        lblImageInfo->setGeometry(QRect(10, 20, 91, 17));
        txtImageInfo = new QLineEdit(tab_8);
        txtImageInfo->setObjectName(QString::fromUtf8("txtImageInfo"));
        txtImageInfo->setGeometry(QRect(110, 10, 341, 31));
        txtImageInfo->setReadOnly(true);
        lblImageSecurityFusing = new QLabel(tab_8);
        lblImageSecurityFusing->setObjectName(QString::fromUtf8("lblImageSecurityFusing"));
        lblImageSecurityFusing->setGeometry(QRect(10, 60, 111, 17));
        txtImageSecurityFusing = new QLineEdit(tab_8);
        txtImageSecurityFusing->setObjectName(QString::fromUtf8("txtImageSecurityFusing"));
        txtImageSecurityFusing->setGeometry(QRect(110, 50, 341, 31));
        txtImageSecurityFusing->setReadOnly(true);
        lblImageVersion = new QLabel(tab_8);
        lblImageVersion->setObjectName(QString::fromUtf8("lblImageVersion"));
        lblImageVersion->setGeometry(QRect(10, 100, 61, 17));
        txtImageVersion = new QLineEdit(tab_8);
        txtImageVersion->setObjectName(QString::fromUtf8("txtImageVersion"));
        txtImageVersion->setGeometry(QRect(110, 90, 341, 31));
        txtImageVersion->setReadOnly(true);
        tabCode->addTab(tab_8, QString());
        btnExportImage = new QPushButton(tab_11);
        btnExportImage->setObjectName(QString::fromUtf8("btnExportImage"));
        btnExportImage->setGeometry(QRect(220, 60, 91, 31));
        tabImg3->addTab(tab_11, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        txtImg3TagVERS = new QLineEdit(tab_2);
        txtImg3TagVERS->setObjectName(QString::fromUtf8("txtImg3TagVERS"));
        txtImg3TagVERS->setGeometry(QRect(130, 20, 81, 31));
        txtImg3TagVERS->setReadOnly(true);
        lblImg3TagVERS = new QLabel(tab_2);
        lblImg3TagVERS->setObjectName(QString::fromUtf8("lblImg3TagVERS"));
        lblImg3TagVERS->setGeometry(QRect(20, 30, 91, 17));
        lblImg3TotalLengthVERS = new QLabel(tab_2);
        lblImg3TotalLengthVERS->setObjectName(QString::fromUtf8("lblImg3TotalLengthVERS"));
        lblImg3TotalLengthVERS->setGeometry(QRect(20, 110, 111, 17));
        lblImg3DataLengthVERS = new QLabel(tab_2);
        lblImg3DataLengthVERS->setObjectName(QString::fromUtf8("lblImg3DataLengthVERS"));
        lblImg3DataLengthVERS->setGeometry(QRect(20, 70, 91, 17));
        txtImg3TotalLengthVERS = new QLineEdit(tab_2);
        txtImg3TotalLengthVERS->setObjectName(QString::fromUtf8("txtImg3TotalLengthVERS"));
        txtImg3TotalLengthVERS->setGeometry(QRect(130, 100, 81, 31));
        txtImg3TotalLengthVERS->setReadOnly(true);
        txtImg3DataLengthVERS = new QLineEdit(tab_2);
        txtImg3DataLengthVERS->setObjectName(QString::fromUtf8("txtImg3DataLengthVERS"));
        txtImg3DataLengthVERS->setGeometry(QRect(130, 60, 81, 31));
        txtImg3DataLengthVERS->setReadOnly(true);
        lblImg3DataVERS = new QLabel(tab_2);
        lblImg3DataVERS->setObjectName(QString::fromUtf8("lblImg3DataVERS"));
        lblImg3DataVERS->setGeometry(QRect(20, 150, 41, 17));
        txtImg3DataVERS = new QLineEdit(tab_2);
        txtImg3DataVERS->setObjectName(QString::fromUtf8("txtImg3DataVERS"));
        txtImg3DataVERS->setGeometry(QRect(130, 140, 361, 31));
        txtImg3DataVERS->setReadOnly(true);
        tabImg3->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        txtImg3TotalLengthSEPO = new QLineEdit(tab_3);
        txtImg3TotalLengthSEPO->setObjectName(QString::fromUtf8("txtImg3TotalLengthSEPO"));
        txtImg3TotalLengthSEPO->setGeometry(QRect(130, 100, 81, 31));
        txtImg3TotalLengthSEPO->setReadOnly(true);
        txtImg3DataLengthSEPO = new QLineEdit(tab_3);
        txtImg3DataLengthSEPO->setObjectName(QString::fromUtf8("txtImg3DataLengthSEPO"));
        txtImg3DataLengthSEPO->setGeometry(QRect(130, 60, 81, 31));
        txtImg3DataLengthSEPO->setReadOnly(true);
        txtImg3TagSEPO = new QLineEdit(tab_3);
        txtImg3TagSEPO->setObjectName(QString::fromUtf8("txtImg3TagSEPO"));
        txtImg3TagSEPO->setGeometry(QRect(130, 20, 81, 31));
        txtImg3TagSEPO->setReadOnly(true);
        lblImg3DataLengthSEPO = new QLabel(tab_3);
        lblImg3DataLengthSEPO->setObjectName(QString::fromUtf8("lblImg3DataLengthSEPO"));
        lblImg3DataLengthSEPO->setGeometry(QRect(20, 70, 91, 17));
        lblImg3TagSEPO = new QLabel(tab_3);
        lblImg3TagSEPO->setObjectName(QString::fromUtf8("lblImg3TagSEPO"));
        lblImg3TagSEPO->setGeometry(QRect(20, 30, 91, 17));
        lblImg3TotalLengthSEPO = new QLabel(tab_3);
        lblImg3TotalLengthSEPO->setObjectName(QString::fromUtf8("lblImg3TotalLengthSEPO"));
        lblImg3TotalLengthSEPO->setGeometry(QRect(20, 110, 111, 17));
        lblImg3DataSEPO = new QLabel(tab_3);
        lblImg3DataSEPO->setObjectName(QString::fromUtf8("lblImg3DataSEPO"));
        lblImg3DataSEPO->setGeometry(QRect(20, 150, 41, 17));
        txtImg3DataSEPO = new QLineEdit(tab_3);
        txtImg3DataSEPO->setObjectName(QString::fromUtf8("txtImg3DataSEPO"));
        txtImg3DataSEPO->setGeometry(QRect(130, 140, 131, 31));
        txtImg3DataSEPO->setReadOnly(true);
        tabImg3->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        lblImg3DataCHIP = new QLabel(tab_4);
        lblImg3DataCHIP->setObjectName(QString::fromUtf8("lblImg3DataCHIP"));
        lblImg3DataCHIP->setGeometry(QRect(20, 150, 41, 17));
        lblImg3TotalLengthCHIP = new QLabel(tab_4);
        lblImg3TotalLengthCHIP->setObjectName(QString::fromUtf8("lblImg3TotalLengthCHIP"));
        lblImg3TotalLengthCHIP->setGeometry(QRect(20, 110, 111, 17));
        txtImg3TotalLengthCHIP = new QLineEdit(tab_4);
        txtImg3TotalLengthCHIP->setObjectName(QString::fromUtf8("txtImg3TotalLengthCHIP"));
        txtImg3TotalLengthCHIP->setGeometry(QRect(130, 100, 81, 31));
        txtImg3TotalLengthCHIP->setReadOnly(true);
        txtImg3TagCHIP = new QLineEdit(tab_4);
        txtImg3TagCHIP->setObjectName(QString::fromUtf8("txtImg3TagCHIP"));
        txtImg3TagCHIP->setGeometry(QRect(130, 20, 81, 31));
        txtImg3TagCHIP->setReadOnly(true);
        txtImg3DataCHIP = new QLineEdit(tab_4);
        txtImg3DataCHIP->setObjectName(QString::fromUtf8("txtImg3DataCHIP"));
        txtImg3DataCHIP->setGeometry(QRect(130, 140, 131, 31));
        txtImg3DataCHIP->setReadOnly(true);
        lblImg3TagCHIP = new QLabel(tab_4);
        lblImg3TagCHIP->setObjectName(QString::fromUtf8("lblImg3TagCHIP"));
        lblImg3TagCHIP->setGeometry(QRect(20, 30, 91, 17));
        txtImg3DataLengthCHIP = new QLineEdit(tab_4);
        txtImg3DataLengthCHIP->setObjectName(QString::fromUtf8("txtImg3DataLengthCHIP"));
        txtImg3DataLengthCHIP->setGeometry(QRect(130, 60, 81, 31));
        txtImg3DataLengthCHIP->setReadOnly(true);
        lblImg3DataLengthCHIP = new QLabel(tab_4);
        lblImg3DataLengthCHIP->setObjectName(QString::fromUtf8("lblImg3DataLengthCHIP"));
        lblImg3DataLengthCHIP->setGeometry(QRect(20, 70, 91, 17));
        tabImg3->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        lblImg3DataLengthBORD = new QLabel(tab_5);
        lblImg3DataLengthBORD->setObjectName(QString::fromUtf8("lblImg3DataLengthBORD"));
        lblImg3DataLengthBORD->setGeometry(QRect(20, 70, 91, 17));
        txtImg3TagBORD = new QLineEdit(tab_5);
        txtImg3TagBORD->setObjectName(QString::fromUtf8("txtImg3TagBORD"));
        txtImg3TagBORD->setGeometry(QRect(130, 20, 81, 31));
        txtImg3TagBORD->setReadOnly(true);
        txtImg3TotalLengthBORD = new QLineEdit(tab_5);
        txtImg3TotalLengthBORD->setObjectName(QString::fromUtf8("txtImg3TotalLengthBORD"));
        txtImg3TotalLengthBORD->setGeometry(QRect(130, 100, 81, 31));
        txtImg3TotalLengthBORD->setReadOnly(true);
        txtImg3DataBORD = new QLineEdit(tab_5);
        txtImg3DataBORD->setObjectName(QString::fromUtf8("txtImg3DataBORD"));
        txtImg3DataBORD->setGeometry(QRect(130, 140, 131, 31));
        txtImg3DataBORD->setReadOnly(true);
        lblImg3TagBORD = new QLabel(tab_5);
        lblImg3TagBORD->setObjectName(QString::fromUtf8("lblImg3TagBORD"));
        lblImg3TagBORD->setGeometry(QRect(20, 30, 91, 17));
        lblImg3TotalLengthBORD = new QLabel(tab_5);
        lblImg3TotalLengthBORD->setObjectName(QString::fromUtf8("lblImg3TotalLengthBORD"));
        lblImg3TotalLengthBORD->setGeometry(QRect(20, 110, 111, 17));
        txtImg3DataLengthBORD = new QLineEdit(tab_5);
        txtImg3DataLengthBORD->setObjectName(QString::fromUtf8("txtImg3DataLengthBORD"));
        txtImg3DataLengthBORD->setGeometry(QRect(130, 60, 81, 31));
        txtImg3DataLengthBORD->setReadOnly(true);
        lblImg3DataBORD = new QLabel(tab_5);
        lblImg3DataBORD->setObjectName(QString::fromUtf8("lblImg3DataBORD"));
        lblImg3DataBORD->setGeometry(QRect(20, 150, 41, 17));
        tabImg3->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        lblImg3TotalLengthSHSH = new QLabel(tab_6);
        lblImg3TotalLengthSHSH->setObjectName(QString::fromUtf8("lblImg3TotalLengthSHSH"));
        lblImg3TotalLengthSHSH->setGeometry(QRect(20, 110, 111, 17));
        txtImg3DataLengthSHSH = new QLineEdit(tab_6);
        txtImg3DataLengthSHSH->setObjectName(QString::fromUtf8("txtImg3DataLengthSHSH"));
        txtImg3DataLengthSHSH->setGeometry(QRect(130, 60, 81, 31));
        txtImg3DataLengthSHSH->setReadOnly(true);
        txtImg3TagSHSH = new QLineEdit(tab_6);
        txtImg3TagSHSH->setObjectName(QString::fromUtf8("txtImg3TagSHSH"));
        txtImg3TagSHSH->setGeometry(QRect(130, 20, 81, 31));
        txtImg3TagSHSH->setReadOnly(true);
        lblImg3DataLengthSHSH = new QLabel(tab_6);
        lblImg3DataLengthSHSH->setObjectName(QString::fromUtf8("lblImg3DataLengthSHSH"));
        lblImg3DataLengthSHSH->setGeometry(QRect(20, 70, 91, 17));
        txtImg3DataSHSH = new QLineEdit(tab_6);
        txtImg3DataSHSH->setObjectName(QString::fromUtf8("txtImg3DataSHSH"));
        txtImg3DataSHSH->setGeometry(QRect(130, 140, 361, 31));
        txtImg3DataSHSH->setReadOnly(true);
        lblImg3TagSHSH = new QLabel(tab_6);
        lblImg3TagSHSH->setObjectName(QString::fromUtf8("lblImg3TagSHSH"));
        lblImg3TagSHSH->setGeometry(QRect(20, 30, 71, 17));
        lblImg3DataSHSH = new QLabel(tab_6);
        lblImg3DataSHSH->setObjectName(QString::fromUtf8("lblImg3DataSHSH"));
        lblImg3DataSHSH->setGeometry(QRect(20, 150, 41, 17));
        txtImg3TotalLengthSHSH = new QLineEdit(tab_6);
        txtImg3TotalLengthSHSH->setObjectName(QString::fromUtf8("txtImg3TotalLengthSHSH"));
        txtImg3TotalLengthSHSH->setGeometry(QRect(130, 100, 81, 31));
        txtImg3TotalLengthSHSH->setReadOnly(true);
        tabImg3->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        txtImg3TagCERT = new QLineEdit(tab_7);
        txtImg3TagCERT->setObjectName(QString::fromUtf8("txtImg3TagCERT"));
        txtImg3TagCERT->setGeometry(QRect(130, 20, 81, 31));
        txtImg3TagCERT->setReadOnly(true);
        txtImg3TotalLengthCERT = new QLineEdit(tab_7);
        txtImg3TotalLengthCERT->setObjectName(QString::fromUtf8("txtImg3TotalLengthCERT"));
        txtImg3TotalLengthCERT->setGeometry(QRect(130, 100, 81, 31));
        txtImg3TotalLengthCERT->setReadOnly(true);
        txtImg3DataLengthCERT = new QLineEdit(tab_7);
        txtImg3DataLengthCERT->setObjectName(QString::fromUtf8("txtImg3DataLengthCERT"));
        txtImg3DataLengthCERT->setGeometry(QRect(130, 60, 81, 31));
        txtImg3DataLengthCERT->setReadOnly(true);
        lblImg3DataLengthCERT = new QLabel(tab_7);
        lblImg3DataLengthCERT->setObjectName(QString::fromUtf8("lblImg3DataLengthCERT"));
        lblImg3DataLengthCERT->setGeometry(QRect(20, 70, 91, 17));
        lblImg3TotalLengthCERT = new QLabel(tab_7);
        lblImg3TotalLengthCERT->setObjectName(QString::fromUtf8("lblImg3TotalLengthCERT"));
        lblImg3TotalLengthCERT->setGeometry(QRect(20, 110, 111, 17));
        lblImg3TagCERT = new QLabel(tab_7);
        lblImg3TagCERT->setObjectName(QString::fromUtf8("lblImg3TagCERT"));
        lblImg3TagCERT->setGeometry(QRect(20, 30, 91, 17));
        btnExportCert = new QPushButton(tab_7);
        btnExportCert->setObjectName(QString::fromUtf8("btnExportCert"));
        btnExportCert->setGeometry(QRect(220, 60, 121, 31));
        tabCERT = new QTabWidget(tab_7);
        tabCERT->setObjectName(QString::fromUtf8("tabCERT"));
        tabCERT->setGeometry(QRect(20, 150, 461, 124));
        tab_13 = new QWidget();
        tab_13->setObjectName(QString::fromUtf8("tab_13"));
        txtImg3TagSDOM = new QLineEdit(tab_13);
        txtImg3TagSDOM->setObjectName(QString::fromUtf8("txtImg3TagSDOM"));
        txtImg3TagSDOM->setGeometry(QRect(100, 10, 81, 31));
        txtImg3TagSDOM->setReadOnly(true);
        lblImg3TagSDOM = new QLabel(tab_13);
        lblImg3TagSDOM->setObjectName(QString::fromUtf8("lblImg3TagSDOM"));
        lblImg3TagSDOM->setGeometry(QRect(10, 20, 71, 17));
        lblImg3DataLengthSDOM = new QLabel(tab_13);
        lblImg3DataLengthSDOM->setObjectName(QString::fromUtf8("lblImg3DataLengthSDOM"));
        lblImg3DataLengthSDOM->setGeometry(QRect(10, 60, 91, 17));
        txtImg3DataLengthSDOM = new QLineEdit(tab_13);
        txtImg3DataLengthSDOM->setObjectName(QString::fromUtf8("txtImg3DataLengthSDOM"));
        txtImg3DataLengthSDOM->setGeometry(QRect(100, 50, 81, 31));
        txtImg3DataLengthSDOM->setReadOnly(true);
        txtImg3TotalLengthSDOM = new QLineEdit(tab_13);
        txtImg3TotalLengthSDOM->setObjectName(QString::fromUtf8("txtImg3TotalLengthSDOM"));
        txtImg3TotalLengthSDOM->setGeometry(QRect(370, 10, 81, 31));
        txtImg3TotalLengthSDOM->setReadOnly(true);
        lblImg3TotalLengthSDOM = new QLabel(tab_13);
        lblImg3TotalLengthSDOM->setObjectName(QString::fromUtf8("lblImg3TotalLengthSDOM"));
        lblImg3TotalLengthSDOM->setGeometry(QRect(260, 20, 111, 17));
        lblImg3DataSDOM = new QLabel(tab_13);
        lblImg3DataSDOM->setObjectName(QString::fromUtf8("lblImg3DataSDOM"));
        lblImg3DataSDOM->setGeometry(QRect(260, 60, 41, 17));
        txtImg3DataSDOM = new QLineEdit(tab_13);
        txtImg3DataSDOM->setObjectName(QString::fromUtf8("txtImg3DataSDOM"));
        txtImg3DataSDOM->setGeometry(QRect(300, 50, 151, 31));
        txtImg3DataSDOM->setReadOnly(true);
        tabCERT->addTab(tab_13, QString());
        tab_14 = new QWidget();
        tab_14->setObjectName(QString::fromUtf8("tab_14"));
        txtImg3TagPROD = new QLineEdit(tab_14);
        txtImg3TagPROD->setObjectName(QString::fromUtf8("txtImg3TagPROD"));
        txtImg3TagPROD->setGeometry(QRect(100, 10, 81, 31));
        txtImg3TagPROD->setReadOnly(true);
        lblImg3TagPROD = new QLabel(tab_14);
        lblImg3TagPROD->setObjectName(QString::fromUtf8("lblImg3TagPROD"));
        lblImg3TagPROD->setGeometry(QRect(10, 20, 71, 17));
        lblImg3DataLengthPROD = new QLabel(tab_14);
        lblImg3DataLengthPROD->setObjectName(QString::fromUtf8("lblImg3DataLengthPROD"));
        lblImg3DataLengthPROD->setGeometry(QRect(10, 60, 91, 17));
        txtImg3DataLengthPROD = new QLineEdit(tab_14);
        txtImg3DataLengthPROD->setObjectName(QString::fromUtf8("txtImg3DataLengthPROD"));
        txtImg3DataLengthPROD->setGeometry(QRect(100, 50, 81, 31));
        txtImg3DataLengthPROD->setReadOnly(true);
        lblImg3TotalLengthPROD = new QLabel(tab_14);
        lblImg3TotalLengthPROD->setObjectName(QString::fromUtf8("lblImg3TotalLengthPROD"));
        lblImg3TotalLengthPROD->setGeometry(QRect(260, 20, 111, 17));
        txtImg3TotalLengthPROD = new QLineEdit(tab_14);
        txtImg3TotalLengthPROD->setObjectName(QString::fromUtf8("txtImg3TotalLengthPROD"));
        txtImg3TotalLengthPROD->setGeometry(QRect(370, 10, 81, 31));
        txtImg3TotalLengthPROD->setReadOnly(true);
        txtImg3DataPROD = new QLineEdit(tab_14);
        txtImg3DataPROD->setObjectName(QString::fromUtf8("txtImg3DataPROD"));
        txtImg3DataPROD->setGeometry(QRect(300, 50, 151, 31));
        txtImg3DataPROD->setReadOnly(true);
        lblImg3DataPROD = new QLabel(tab_14);
        lblImg3DataPROD->setObjectName(QString::fromUtf8("lblImg3DataPROD"));
        lblImg3DataPROD->setGeometry(QRect(260, 60, 41, 17));
        tabCERT->addTab(tab_14, QString());
        tab_15 = new QWidget();
        tab_15->setObjectName(QString::fromUtf8("tab_15"));
        lblImg3DataCHIPcert = new QLabel(tab_15);
        lblImg3DataCHIPcert->setObjectName(QString::fromUtf8("lblImg3DataCHIPcert"));
        lblImg3DataCHIPcert->setGeometry(QRect(260, 60, 41, 17));
        lblImg3TagCHIPcert = new QLabel(tab_15);
        lblImg3TagCHIPcert->setObjectName(QString::fromUtf8("lblImg3TagCHIPcert"));
        lblImg3TagCHIPcert->setGeometry(QRect(10, 20, 71, 17));
        txtImg3TotalLengthCHIPcert = new QLineEdit(tab_15);
        txtImg3TotalLengthCHIPcert->setObjectName(QString::fromUtf8("txtImg3TotalLengthCHIPcert"));
        txtImg3TotalLengthCHIPcert->setGeometry(QRect(370, 10, 81, 31));
        txtImg3TotalLengthCHIPcert->setReadOnly(true);
        txtImg3TagCHIPcert = new QLineEdit(tab_15);
        txtImg3TagCHIPcert->setObjectName(QString::fromUtf8("txtImg3TagCHIPcert"));
        txtImg3TagCHIPcert->setGeometry(QRect(100, 10, 81, 31));
        txtImg3TagCHIPcert->setReadOnly(true);
        txtImg3DataCHIPcert = new QLineEdit(tab_15);
        txtImg3DataCHIPcert->setObjectName(QString::fromUtf8("txtImg3DataCHIPcert"));
        txtImg3DataCHIPcert->setGeometry(QRect(300, 50, 151, 31));
        txtImg3DataCHIPcert->setReadOnly(true);
        lblImg3TotalLengthCHIPcert = new QLabel(tab_15);
        lblImg3TotalLengthCHIPcert->setObjectName(QString::fromUtf8("lblImg3TotalLengthCHIPcert"));
        lblImg3TotalLengthCHIPcert->setGeometry(QRect(260, 20, 111, 17));
        txtImg3DataLengthCHIPcert = new QLineEdit(tab_15);
        txtImg3DataLengthCHIPcert->setObjectName(QString::fromUtf8("txtImg3DataLengthCHIPcert"));
        txtImg3DataLengthCHIPcert->setGeometry(QRect(100, 50, 81, 31));
        txtImg3DataLengthCHIPcert->setReadOnly(true);
        lblImg3DataLengthCHIPcert = new QLabel(tab_15);
        lblImg3DataLengthCHIPcert->setObjectName(QString::fromUtf8("lblImg3DataLengthCHIPcert"));
        lblImg3DataLengthCHIPcert->setGeometry(QRect(10, 60, 91, 17));
        tabCERT->addTab(tab_15, QString());
        tabImg3->addTab(tab_7, QString());
        lblImgVersion = new QLabel(centralwidget);
        lblImgVersion->setObjectName(QString::fromUtf8("lblImgVersion"));
        lblImgVersion->setGeometry(QRect(20, 110, 91, 17));
        txtImgVersion = new QLineEdit(centralwidget);
        txtImgVersion->setObjectName(QString::fromUtf8("txtImgVersion"));
        txtImgVersion->setGeometry(QRect(140, 100, 51, 31));
        txtImgVersion->setReadOnly(true);
        lblSoftwareVersion = new QLabel(centralwidget);
        lblSoftwareVersion->setObjectName(QString::fromUtf8("lblSoftwareVersion"));
        lblSoftwareVersion->setGeometry(QRect(230, 0, 271, 45));
        lblSoftwareVersion->setFont(font);
        lblCopyrights = new QLabel(centralwidget);
        lblCopyrights->setObjectName(QString::fromUtf8("lblCopyrights"));
        lblCopyrights->setGeometry(QRect(230, 510, 291, 17));
        ImgToolGUIClass->setCentralWidget(centralwidget);
        menubar = new QMenuBar(ImgToolGUIClass);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 544, 27));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        ImgToolGUIClass->setMenuBar(menubar);
        statusbar = new QStatusBar(ImgToolGUIClass);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        ImgToolGUIClass->setStatusBar(statusbar);

        menubar->addAction(menuFile->menuAction());
        menuFile->addAction(btnMenuOpenFile);
        menuFile->addAction(btnMenuExit);

        retranslateUi(ImgToolGUIClass);
        QObject::connect(btnMenuExit, SIGNAL(triggered()), ImgToolGUIClass, SLOT(close()));

        tabImg3->setCurrentIndex(0);
        tabCode->setCurrentIndex(0);
        tabCERT->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(ImgToolGUIClass);
    } // setupUi

    void retranslateUi(QMainWindow *ImgToolGUIClass)
    {
        ImgToolGUIClass->setWindowTitle(QApplication::translate("ImgToolGUIClass", "ImgTool v1.0b (1A0116c)", 0, QApplication::UnicodeUTF8));
        btnMenuOpenFile->setText(QApplication::translate("ImgToolGUIClass", "Open", 0, QApplication::UnicodeUTF8));
        btnMenuExit->setText(QApplication::translate("ImgToolGUIClass", "Exit", 0, QApplication::UnicodeUTF8));
        lblMainTitle->setText(QApplication::translate("ImgToolGUIClass", "ImgTool", 0, QApplication::UnicodeUTF8));
        lblFilePath->setText(QApplication::translate("ImgToolGUIClass", "Selected File Path :", 0, QApplication::UnicodeUTF8));
        lblImgFullSize->setText(QApplication::translate("ImgToolGUIClass", "Full Size :", 0, QApplication::UnicodeUTF8));
        lblImgVersionTab->setText(QApplication::translate("ImgToolGUIClass", "Version :", 0, QApplication::UnicodeUTF8));
        lblImgFullSizeNoHeader->setText(QApplication::translate("ImgToolGUIClass", "Full Size without Header :", 0, QApplication::UnicodeUTF8));
        lblImg3SignatureCheckArea->setText(QApplication::translate("ImgToolGUIClass", "Signature Check Area :", 0, QApplication::UnicodeUTF8));
        lblImg3ID->setText(QApplication::translate("ImgToolGUIClass", "Identifier :", 0, QApplication::UnicodeUTF8));
        tabImg3->setTabText(tabImg3->indexOf(tab), QApplication::translate("ImgToolGUIClass", "Header", 0, QApplication::UnicodeUTF8));
        lblImg3TagTYPE->setText(QApplication::translate("ImgToolGUIClass", "Tag Name :", 0, QApplication::UnicodeUTF8));
        lblImg3TotalLengthTYPE->setText(QApplication::translate("ImgToolGUIClass", "Tag Total Length :", 0, QApplication::UnicodeUTF8));
        lblImg3LengthTagTYPE->setText(QApplication::translate("ImgToolGUIClass", "Data Length :", 0, QApplication::UnicodeUTF8));
        tabImg3->setTabText(tabImg3->indexOf(tab_10), QApplication::translate("ImgToolGUIClass", "TYPE", 0, QApplication::UnicodeUTF8));
        lblImg3TagDATA->setText(QApplication::translate("ImgToolGUIClass", "Tag Name :", 0, QApplication::UnicodeUTF8));
        lblImg3TotalLengthDATA->setText(QApplication::translate("ImgToolGUIClass", "Tag Total Length :", 0, QApplication::UnicodeUTF8));
        lblImg3DataLengthDATA->setText(QApplication::translate("ImgToolGUIClass", "Data Length :", 0, QApplication::UnicodeUTF8));
        lblImageInfo->setText(QApplication::translate("ImgToolGUIClass", "Information :", 0, QApplication::UnicodeUTF8));
        lblImageSecurityFusing->setText(QApplication::translate("ImgToolGUIClass", "Security Fusing :", 0, QApplication::UnicodeUTF8));
        lblImageVersion->setText(QApplication::translate("ImgToolGUIClass", "Version :", 0, QApplication::UnicodeUTF8));
        tabCode->setTabText(tabCode->indexOf(tab_8), QApplication::translate("ImgToolGUIClass", "Image", 0, QApplication::UnicodeUTF8));
        btnExportImage->setText(QApplication::translate("ImgToolGUIClass", "Export image", 0, QApplication::UnicodeUTF8));
        tabImg3->setTabText(tabImg3->indexOf(tab_11), QApplication::translate("ImgToolGUIClass", "DATA", 0, QApplication::UnicodeUTF8));
        lblImg3TagVERS->setText(QApplication::translate("ImgToolGUIClass", "Tag Name :", 0, QApplication::UnicodeUTF8));
        lblImg3TotalLengthVERS->setText(QApplication::translate("ImgToolGUIClass", "Tag Total Length :", 0, QApplication::UnicodeUTF8));
        lblImg3DataLengthVERS->setText(QApplication::translate("ImgToolGUIClass", "Data Length :", 0, QApplication::UnicodeUTF8));
        lblImg3DataVERS->setText(QApplication::translate("ImgToolGUIClass", "Data :", 0, QApplication::UnicodeUTF8));
        tabImg3->setTabText(tabImg3->indexOf(tab_2), QApplication::translate("ImgToolGUIClass", "VERS", 0, QApplication::UnicodeUTF8));
        lblImg3DataLengthSEPO->setText(QApplication::translate("ImgToolGUIClass", "Data Length :", 0, QApplication::UnicodeUTF8));
        lblImg3TagSEPO->setText(QApplication::translate("ImgToolGUIClass", "Tag Name :", 0, QApplication::UnicodeUTF8));
        lblImg3TotalLengthSEPO->setText(QApplication::translate("ImgToolGUIClass", "Tag Total Length :", 0, QApplication::UnicodeUTF8));
        lblImg3DataSEPO->setText(QApplication::translate("ImgToolGUIClass", "Data :", 0, QApplication::UnicodeUTF8));
        tabImg3->setTabText(tabImg3->indexOf(tab_3), QApplication::translate("ImgToolGUIClass", "SEPO", 0, QApplication::UnicodeUTF8));
        lblImg3DataCHIP->setText(QApplication::translate("ImgToolGUIClass", "Data :", 0, QApplication::UnicodeUTF8));
        lblImg3TotalLengthCHIP->setText(QApplication::translate("ImgToolGUIClass", "Tag Total Length :", 0, QApplication::UnicodeUTF8));
        lblImg3TagCHIP->setText(QApplication::translate("ImgToolGUIClass", "Tag Name :", 0, QApplication::UnicodeUTF8));
        lblImg3DataLengthCHIP->setText(QApplication::translate("ImgToolGUIClass", "Data Length :", 0, QApplication::UnicodeUTF8));
        tabImg3->setTabText(tabImg3->indexOf(tab_4), QApplication::translate("ImgToolGUIClass", "CHIP", 0, QApplication::UnicodeUTF8));
        lblImg3DataLengthBORD->setText(QApplication::translate("ImgToolGUIClass", "Data Length :", 0, QApplication::UnicodeUTF8));
        lblImg3TagBORD->setText(QApplication::translate("ImgToolGUIClass", "Tag Name :", 0, QApplication::UnicodeUTF8));
        lblImg3TotalLengthBORD->setText(QApplication::translate("ImgToolGUIClass", "Tag Total Length :", 0, QApplication::UnicodeUTF8));
        lblImg3DataBORD->setText(QApplication::translate("ImgToolGUIClass", "Data :", 0, QApplication::UnicodeUTF8));
        tabImg3->setTabText(tabImg3->indexOf(tab_5), QApplication::translate("ImgToolGUIClass", "BORD", 0, QApplication::UnicodeUTF8));
        lblImg3TotalLengthSHSH->setText(QApplication::translate("ImgToolGUIClass", "Tag Total Length :", 0, QApplication::UnicodeUTF8));
        lblImg3DataLengthSHSH->setText(QApplication::translate("ImgToolGUIClass", "Data Length :", 0, QApplication::UnicodeUTF8));
        lblImg3TagSHSH->setText(QApplication::translate("ImgToolGUIClass", "Tag Name :", 0, QApplication::UnicodeUTF8));
        lblImg3DataSHSH->setText(QApplication::translate("ImgToolGUIClass", "Data :", 0, QApplication::UnicodeUTF8));
        tabImg3->setTabText(tabImg3->indexOf(tab_6), QApplication::translate("ImgToolGUIClass", "SHSH", 0, QApplication::UnicodeUTF8));
        lblImg3DataLengthCERT->setText(QApplication::translate("ImgToolGUIClass", "Data Length :", 0, QApplication::UnicodeUTF8));
        lblImg3TotalLengthCERT->setText(QApplication::translate("ImgToolGUIClass", "Tag Total Length :", 0, QApplication::UnicodeUTF8));
        lblImg3TagCERT->setText(QApplication::translate("ImgToolGUIClass", "Tag Name :", 0, QApplication::UnicodeUTF8));
        btnExportCert->setText(QApplication::translate("ImgToolGUIClass", "Export Certificate", 0, QApplication::UnicodeUTF8));
        lblImg3TagSDOM->setText(QApplication::translate("ImgToolGUIClass", "Tag Name :", 0, QApplication::UnicodeUTF8));
        lblImg3DataLengthSDOM->setText(QApplication::translate("ImgToolGUIClass", "Data Length :", 0, QApplication::UnicodeUTF8));
        lblImg3TotalLengthSDOM->setText(QApplication::translate("ImgToolGUIClass", "Tag Total Length :", 0, QApplication::UnicodeUTF8));
        lblImg3DataSDOM->setText(QApplication::translate("ImgToolGUIClass", "Data :", 0, QApplication::UnicodeUTF8));
        tabCERT->setTabText(tabCERT->indexOf(tab_13), QApplication::translate("ImgToolGUIClass", "SDOM", 0, QApplication::UnicodeUTF8));
        lblImg3TagPROD->setText(QApplication::translate("ImgToolGUIClass", "Tag Name :", 0, QApplication::UnicodeUTF8));
        lblImg3DataLengthPROD->setText(QApplication::translate("ImgToolGUIClass", "Data Length :", 0, QApplication::UnicodeUTF8));
        lblImg3TotalLengthPROD->setText(QApplication::translate("ImgToolGUIClass", "Tag Total Length :", 0, QApplication::UnicodeUTF8));
        lblImg3DataPROD->setText(QApplication::translate("ImgToolGUIClass", "Data :", 0, QApplication::UnicodeUTF8));
        tabCERT->setTabText(tabCERT->indexOf(tab_14), QApplication::translate("ImgToolGUIClass", "PROD", 0, QApplication::UnicodeUTF8));
        lblImg3DataCHIPcert->setText(QApplication::translate("ImgToolGUIClass", "Data :", 0, QApplication::UnicodeUTF8));
        lblImg3TagCHIPcert->setText(QApplication::translate("ImgToolGUIClass", "Tag Name :", 0, QApplication::UnicodeUTF8));
        lblImg3TotalLengthCHIPcert->setText(QApplication::translate("ImgToolGUIClass", "Tag Total Length :", 0, QApplication::UnicodeUTF8));
        lblImg3DataLengthCHIPcert->setText(QApplication::translate("ImgToolGUIClass", "Data Length :", 0, QApplication::UnicodeUTF8));
        tabCERT->setTabText(tabCERT->indexOf(tab_15), QApplication::translate("ImgToolGUIClass", "CHIP", 0, QApplication::UnicodeUTF8));
        tabImg3->setTabText(tabImg3->indexOf(tab_7), QApplication::translate("ImgToolGUIClass", "CERT", 0, QApplication::UnicodeUTF8));
        lblImgVersion->setText(QApplication::translate("ImgToolGUIClass", "Img Version :", 0, QApplication::UnicodeUTF8));
        lblSoftwareVersion->setText(QApplication::translate("ImgToolGUIClass", "v1.0 (1A0116d)", 0, QApplication::UnicodeUTF8));
        lblCopyrights->setText(QApplication::translate("ImgToolGUIClass", "\302\251 2016 Pierre-Marc Bonneau, all rights reserved.", 0, QApplication::UnicodeUTF8));
        menuFile->setTitle(QApplication::translate("ImgToolGUIClass", "File", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class ImgToolGUIClass: public Ui_ImgToolGUIClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_IMGTOOLGUI_H
